# Generated by Django 3.2.13 on 2022-04-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=100)),
                ('value_type', models.CharField(choices=[('radio', 'radio'), ('dropdown', 'dropdown'), ('null', 'null')], max_length=100)),
                ('owner', models.CharField(choices=[('individual', 'individual'), ('company', 'company')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('Cng/lpg', 'Cng/lpg'), ('petrol', 'petrol'), ('elec', 'elec'), ('all', 'all')], max_length=20)),
                ('policy_type', models.CharField(choices=[('New', 'New'), ('comp', 'comp'), ('tp', 'tp'), ('od', 'od'), ('all', 'all')], max_length=10)),
            ],
        ),
    ]
