# Generated by Django 3.2.13 on 2022-04-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Cng/lpg', 'Cng/lpg'), ('petrol', 'petrol'), ('elec', 'elec'), ('all', 'all')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cover',
            name='owner',
            field=models.CharField(blank=True, choices=[('individual', 'individual'), ('company', 'company'), ('all', 'all')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cover',
            name='policy_type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('comp', 'comp'), ('tp', 'tp'), ('od', 'od'), ('all', 'all')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cover',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cover',
            name='value_type',
            field=models.CharField(blank=True, choices=[('radio', 'radio'), ('dropdown', 'dropdown'), ('null', 'null')], max_length=100, null=True),
        ),
    ]
