# Generated by Django 3.2.13 on 2022-04-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20220420_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
