# Generated by Django 3.2.13 on 2022-04-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_alter_cover_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('FW', 'FW'), ('TW', 'TW'), ('GCV', 'GCV'), ('PCV', 'PCV'), ('all', 'all')], max_length=100, null=True),
        ),
    ]
