# Generated by Django 3.2.13 on 2022-04-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_auto_20220420_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Policy_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cover',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='cover',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='cover',
            name='policy_type',
        ),
        migrations.AlterField(
            model_name='cover',
            name='value_type',
            field=models.CharField(blank=True, choices=[('null', 'null'), ('dropdown', 'dropdown')], default='null', max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='cover',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='cover',
            name='owner_type',
            field=models.ManyToManyField(blank=True, to='basic.Owner_type'),
        ),
        migrations.AddField(
            model_name='cover',
            name='fuel_type',
            field=models.ManyToManyField(blank=True, to='basic.Fuel_type'),
        ),
        migrations.AddField(
            model_name='cover',
            name='policy_type',
            field=models.ManyToManyField(blank=True, to='basic.Policy_type'),
        ),
        migrations.AddField(
            model_name='cover',
            name='vehicle_type',
            field=models.ManyToManyField(blank=True, to='basic.Vehicle_type'),
        ),
    ]
