# Generated by Django 3.2.13 on 2022-04-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20220421_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('Own_Damage', 'Own_Damage'), ('Liability', 'Liability'), ('Addon', 'Addon'), ('Discounts', 'Discounts')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cover',
            name='cover_type',
            field=models.CharField(blank=True, choices=[('Motor', 'Motor'), ('Life', 'Life'), ('Health', 'Health')], max_length=100, null=True),
        ),
    ]
