# Generated by Django 3.2.13 on 2022-04-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_alter_cover_owner_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cover_type',
        ),
        migrations.AddField(
            model_name='cover',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cover',
            name='value_type',
            field=models.CharField(blank=True, choices=[('null', 'null'), ('dropdown', 'dropdown'), ('radio', 'radio'), ('text', 'text')], default='null', max_length=100, null=True),
        ),
    ]
